name: serverless-hs-examples
version: 0.0.1
maintainer: Utku Demir <utdemir@gmail.com>
license: BSD3
github: utdemir/serverless-hs
category: Web

ghc-options: >
  -threaded -rtsopts -with-rtsopts=-N
  -static -optl-static -optl-pthread -fPIC 
  
executables:
  simple:
    main: Simple.hs
    dependencies:
      - base >= 4.7 && < 5
      - aeson
      - serverless-hs

